[General settings]
Program Type=Portable
Destination folder=C:\MCY\Download
Audio Quality=320k
Save Logs=Yes
Check updates=Yes
language=es
[accessibility]
Enable enanced accessibility=Yes
Speak Whit=NVDA
Announce position=1
Read download progress bar=Yes
Read download remaining time=No
Beep for progress bars=Yes
[misc]
motdversion=8
Show tips=1
Last radio loaded=http://stream.zeno.fm/1d6tptefguhvv
[search]
Number of results=25
