[Language config]
Langname=Español
langversion=1.1
[Translate text]
Error=Error!
Err_not_comp=tu arquitectura es de 32 bits y por lo tanto no está soportada en este programa. Ten en cuenta que el soporte para 32 bits terminó el 27 de mayo de 2020.
Langselector=Selecciona un idioma con las flechas arriba y abajo, o, si eres una persona con visión, también puedes tocar el menú contextual para hacerlo.
Downloadingmot=Descargando mensaje del día...
Motdlabel=Espera, por favor.
SetTitle=Descargador de músicas de YouTube, por Mateo Cedillo
Version=Versión
Gr1=Saludos
Gr2=un gusto verte, 
Gr3=Y Bienvenido a MCY downloader, 
Grbox=Te damos la bienvenida
Ytupdate=Buscando actualización de YouTubeDl, esto puede tardar un momento
CheckingUp=Buscando actualizaciones...
YtUpdateTip=Buscando actualizaciones para la librería YouTubeDl, esto puede llevar un tiempo. Por favor esperar...
Tr1=Por favor espera
Tr2=Espera mientras se está buscando la actualización de la librería de YouTube
[Menu]
GuiWindow=Descargador de músicas de YouTube, por Mateo Cedillo
Downloadmenu=&descargar
Downloaditem1=Descargar en audio mp3...
Downloaditem2=Salir
Helpmenu=Ayuda
Helpitem1=Reportero de errores...
helpitem2=Buscar actualizaciones...
helpitem3=Acerca de...
GuiLabel=Pulsa alt para abrir el menú.
Exitbutton=Salir
[Objetibe]
Enterlink=Introduzca una URL
Enterlink2=Inserte aquí el enlace del vídeo a descargar:
Preparing=Descargando
Preparing2=Espera un momento, estamos buscando el vídeo.
Downloading=Estamos descargando tu vídeo.
[Help]
Item1=Acerca de...
Item2=Programa desarrollado por mateo cedillo para descargar videos a través de Youtube. 2018-2020 MT programs.
LErrorReporting=Cargando reportero de errores...
[Audio]
;En esta sección debes realizar grabaciones en voz alta y clara. Ten en cuenta que el formato de estas grabaciones deben estar en .wav.
text1=Por favor, selecciona un idioma con las flechas arriba y abajo de tu teclado.
Text2=NombreIdioma
Text3=¡Error!
Text4=Actualización completada! Por favor, espera...
Text5=Descargando, espera por favor.
Text6=Resumiendo el manual del usuario.